services:
    vault:
        image: hashicorp/vault:1.13.3
        container_name: vault
        restart: on-failure:10
        ports:
            - '8201:8201' #? UI
            - '8200:8200' #? TCP connection
        environment:
            VAULT_ADDR: 'https://0.0.0.0:8201'
            VAULT_API_ADDR: 'https://0.0.0.0:8201'
            # VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/data/vault_volume/vault.pem", "tls_key_file":"/data/vault_volume/vault-key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
            VAULT_DEV_ROOT_TOKEN_ID: 'token'
            VAULT_TOKEN: 'token'
        cap_add:
            - IPC_LOCK
        volumes:
            - vault_data:/data
            - ./vault_volume:/data/vault_volume
        healthcheck:
            retries: 5
        command: server -dev -dev-root-token-id="token"
volumes:
  vault_data: {}